birthday=input("Enter Your Birthday in DD/MM/YY ")
borns=input("Enter Your Birthday in YYYY/MM/DD ")
birthdays=input("Enter Yiur Brithday in DDth Month, YY ")
born=input("Enter Your Birthday in Month DD, YYYY ")
happybirthday=input("Enter Your Birthday in MM.DD.YY ")
print("Your Birthday is",birthdays)
print("Your Birthday is",born)
print("Your Birthday is",birthday)
print("Your Birthday is",borns)
print("Your Birthday is",happybirthday)
